# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b66ca63bacb678f37972f6e149641cde7a406d31373d5f5513990cc84c6e8338ad9a9639c04c2b9b65a38e9e2c8d7b560ab5be3b5f5f0deb352ddbeaff5a257

test:
  secret_key_base: 2f1698caed5ae6f28103ea8087fbbbebb24cf68e702e1fdb3243c980726b88cd27ccdf4bdbe8cceb348fc1b52e053ddd66c63dae46febb2a0af82d08dcdff5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
